### ISSUE TITLE
hello-world practice may be failed in the test framework?

### ISSUE THREAD

**Issue by hl4** [exercism/wren#102]
I am trying to learn wren language. The Hello-World practice runs into the following error after I submitted the code.

```
[wren-testie-wrapper/testie line 9] Error at 'return': A constructor cannot return a value.
Could not compile module 'wren-testie-wrapper/testie'.
at (script) (./hello-world.spec.wren line 1)
```

Here is my code. Although I think it has nothing to do with the issue. 

```
class Hello {
    static world() {
        return "Hello, World!"
    }
}
```

Thanks for presenting this practice.

**Comment by joshgoebel** [comment]
https://github.com/exercism/wren-test-runner/pull/27

As soon as someone signs off the fix will be deployed.  Sorry about that.

**Comment by joshgoebel** [comment]
@hl4 Give it another shot now?
