### ISSUE TITLE
Is this track still maintained?

### ISSUE THREAD

**Issue by glennj** [exercism/wren#155]
@joshgoebel are you still active in wren?

**Comment by joshgoebel** [comment]
I'm still around but pretty busy these days, but let me know if you really need something.

**Comment by ErikSchierboom** [comment]
@glennj Just to be safe, you still want to be added as a maintainer?

**Comment by glennj** [comment]
yes

**Comment by ErikSchierboom** [comment]
Ah, I see that @iHiD has already added you! Thanks for helping out.
