### ISSUE TITLE
Check docs are up to date

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/wren#50]
Please check if your documentation files are still up-to-date.

The key documentation files to check are:

- [x] `docs/ABOUT.md`
- [x] `docs/INSTALLATION.md`
- [x] `docs/LEARNING.md`
- [x] `docs/RESOURCES.md`
- [x] `docs/TESTS.md`
- [x] `exercises/shared/.docs/help.md`
- [x] `exercises/shared/.docs/tests.md`

There might be more.

## Link check report

To help identify invalid links, we've automatically checked the links of _all_ `*.md` files in this repo.
This is the report of that check:

<pre style="color:#bbb;white-space:pre-wrap;word-wrap:break-word;overflow-wrap:break-word">📝 Summary
---------------------
🔍 Total...........60
✅ Successful......60
⏳ Timeouts.........0
🔀 Redirected.......0
👻 Excluded.........0
🚫 Errors...........0

</pre>
## Tracking

https://github.com/exercism/v3-launch/issues/54

**Comment by joshgoebel** [comment]
I believe all the docs should be passable now.
