### ISSUE TITLE
Need `wren-representer` repo for Wren Representer

### ISSUE THREAD

**Issue by joshgoebel** [exercism/wren#9]
> If you would like to get involved in helping with an existing Representer, please open an issue in its repository asking if there is somewhere you can help. If you would like to create a Representer for a language that currently does not have one, please follow the creating a Representer instructions.

LInk was broken... can I get a `wren-representer` repo... with template if there is one...

**Comment by iHiD** [comment]
https://github.com/exercism/wren-representer

**Comment by iHiD** [comment]
There's no template. Basically:
- Docker file (same as test runner)
- bin/run.sh (same as test runner)
- Something which returns the input as an AST (or even easier returns input as output)
- Some mapping.json if you normalise, else `{}`
- Add terraform, etc
